config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'landing#index'

  #Admin tools
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'sidekiq' => redirect('/')

  devise_for :users, {controllers: { registrations: 'registrations', omniauth_callbacks: 'oauths' }}
  devise_scope :user do
    get 'login/password', to: 'devise/sessions#new', as: :'password_login'
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'signup/password', to: 'devise/registrations#new', as: :signup
  end

  resource :passwordless_link, only: :create do
    get 'login', to: 'passwordless_links#login'
  end

  get 'login', to: 'passwordless_links#request_link', as: :passwordless_link_login

  get 'signup' => 'passwordless_links#register_link', as: :passwordless_link_signup
  post 'signup' => 'passwordless_links#register', as: :signup_passwordless_link

  get '/lobby', to: 'home#index', as: :home

  post "/early-access" => "landing#early_access", :as => :early_access

  post '/room/:identifier/panel-update' => "room#panel_update", :as => :panel_update
  get '/room/new' => "room#join_room", :as => :new_room
  get '/room/:identifier' => "room#join_room", :as => :room

  get '/room_participant/:employee_id' => "room#participant_data"
  post '/room-participant' => "room#update_participant"

  get '/session/:identifier' => "jally_session#join_session", :as => :jally_session
  post '/session' => "jally_session#join_session", :as => :create_jally_session
  post '/session-room' => "jally_session#get_room", :as => :get_session_room

  post '/profile' => "profile#update_profile", :as => :update_profile
  post '/company' => "company#join_company", :as => :join_company
  post '/invite' => "profile#invite_users", :as => :invite_users
  get '/join_playspace/:invite_code' => "company#accept_invitation", :as => :accept_invitation

  get '/game/:game_slug' => "game#game_data", :as => :fetch_game_data

  get '/feedback/:type' => "feedback#show", :as => :show_feedback
  post '/feedback/:type' => "feedback#submit", :as => :submit_feedback
end

app/controllers/passwordless_links_controller.rb
# frozen_string_literal: true

class PasswordlessLinksController < ApplicationController
  def request_link
    if user_signed_in?
      return redirect_to root_path, flash: { warning: "You are already logged in" }
    end

    render layout: "home"
  end

  def register_link
    if user_signed_in?
      return redirect_to root_path, flash: { warning: "You are already logged in" }
    end

    render layout: "home"
  end

  def create
    if params[:email].blank?
      return redirect_to passwordless_link_login_path, flash: { warning: "Email can't be empty." }
    end

    email_requested = params[:email]
    @user = User.find_by(email: email_requested) || User.where("email ILIKE ?", email_requested).first
    if @user.blank?
      return redirect_to passwordless_link_login_path, flash: {
          warning: "Uh oh! There is no account with that email. Please use the email you signed up with or sign up using the link below."
      }
    end
    PasswordlessLinkService.new(@user).send_token!

    redirect_to passwordless_link_login_path, flash: { success: "We just sent the magic link to #{email_requested}." }
  end

  def register
    if params[:email].blank?
      return redirect_to passwordless_link_signup_path, flash: { warning: "Email invalid." }
    end

    if params["checkField"].present?
      # Spam Likely, filled out a hidden field
      Rails.logger.debug("Likely spam submission #{params}")
      Slack.spam_request(params)
      redirect_to root_path and return
    end

    email_requested = params[:email]

    @user = User.find_by(email: email_requested) || User.where("email ILIKE ?", email_requested).first
    new_user = @user.nil?
    @user ||= User.create!(email: email_requested,
                         password: SecureRandom.alphanumeric(8))

    PasswordlessLinkService.new(@user).send_token!(sign_up: new_user)

    Slack.new_sign_up({email: email_requested})

    request_page = params[:requestPage]


    if request_page == 'lander'
      redirect_to root_path, flash: { success: "We just sent the magic link to #{email_requested}." }
    else
      redirect_to passwordless_link_signup_path, flash: { success: "We just sent the magic link to #{email_requested}." }
    end
  end

  def login
    if params[:token].blank?
      return redirect_to passwordless_link_login_path
    end
    user_id, token = params.require([:user, :token])
    redir_path = params[:after_sign_in]

    @user = User.find_by(id: user_id)
    passwordless_link_service = PasswordlessLinkService.new(@user)

    if user_signed_in?
      if current_user == @user && passwordless_link_service.validate_token(token)
        passwordless_link_service.reset_token_info!
      end
      if redir_path && (redir_path =~ /^\/[^\/\\]/) # make sure it's relative
        return redirect_to redir_path, flash: { warning: "You are already logged in" }
      else
        return redirect_to root_path, flash: { warning: "You are already logged in" }
      end
    end

    if @user && passwordless_link_service.validate_token(token)
      passwordless_link_service.reset_token_info!
      if redir_path && (redir_path =~ /^\/[^\/\\]/) # make sure it's relative
        session[:after_sign_in] = redir_path
      end
      sign_in_and_redirect @user
    else
      redirect_to passwordless_link_login_path, flash: { warning: "The link is invalid or has expired" }
    end
  end
end

app/views/passwordless_links/register_link.html.erb
<div class="columns is-centered is-mobile">
  <div class="column is-three-quarters-mobile is-two-thirds-tablet
    is-half-desktop is-one-third-widescreen is-one-third-fullhd has-text-centered">
    <h1 class="title mt-6">Sign up to Jally</h1>

    <%= form_with url: signup_passwordless_link_path, method: :post, local: true do |f| %>
      <% flash.each do |message_type, message| %>
        <div class="notification is-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>

      <div class="field">
        <div class="control has-icons-left">
          <%= f.email_field :email, autocomplete: "email",
                            class: "input", required: 'true',
                            placeholder: "name@work-email.com" %>
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Continue with email", class: "button jally-button is-fullwidth mb-3" %>
      </div>
    <% end %>

    <div class="notification is-primary is-light">
      ⚡ We’ll send you a magic link to confirm your email address.
    </div>

    <div>
      Already have an account? <a href="<%= passwordless_link_login_path %>">Login</a>
    </div>

  </div>
</div>

app/views/passwordless_links/request_link.html.erb
<div class="columns is-centered is-mobile">
  <div class="column is-three-quarters-mobile is-two-thirds-tablet
    is-half-desktop is-one-third-widescreen is-one-third-fullhd has-text-centered">
    <h1 class="title mt-6">Sign in to Jally</h1>

    <%= form_with url: passwordless_link_path, method: :post, local: true do |f| %>
      <% flash.each do |message_type, message| %>
        <div class="notification is-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>

      <div class="field">
        <div class="control has-icons-left">
          <%= f.email_field :email, autofocus: true,
                            autocomplete: "email", class: "input",
                            required: 'true', placeholder: "name@work-email.com" %>
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Sign in with email", class: "button jally-button is-fullwidth mb-3" %>
      </div>
    <% end %>

    <div class="notification is-primary is-light">
      ⚡ We’ll email you a magic link for signing in without a password. Or you can <%= link_to "login manually", password_login_path %>.<br />
    </div>

    <div>
      Don't have an account yet? <a href="<%= passwordless_link_signup_path %>">Sign up</a>
    </div>
  </div>
</div>