config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'landing#index'

  #Admin tools
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'sidekiq' => redirect('/')

  devise_for :users, {controllers: { registrations: 'registrations', omniauth_callbacks: 'oauths' }}
  devise_scope :user do
    get 'login/password', to: 'devise/sessions#new', as: :'password_login'
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'signup/password', to: 'devise/registrations#new', as: :signup
  end

  resource :passwordless_link, only: :create do
    get 'login', to: 'passwordless_links#login'
  end

  get 'login', to: 'passwordless_links#request_link', as: :passwordless_link_login

  get 'signup' => 'passwordless_links#register_link', as: :passwordless_link_signup
  post 'signup' => 'passwordless_links#register', as: :signup_passwordless_link

  get '/lobby', to: 'home#index', as: :home

  post "/early-access" => "landing#early_access", :as => :early_access

  post '/room/:identifier/panel-update' => "room#panel_update", :as => :panel_update
  get '/room/new' => "room#join_room", :as => :new_room
  get '/room/:identifier' => "room#join_room", :as => :room

  get '/room_participant/:employee_id' => "room#participant_data"
  post '/room-participant' => "room#update_participant"

  get '/session/:identifier' => "jally_session#join_session", :as => :jally_session
  post '/session' => "jally_session#join_session", :as => :create_jally_session
  post '/session-room' => "jally_session#get_room", :as => :get_session_room

  post '/profile' => "profile#update_profile", :as => :update_profile
  post '/company' => "company#join_company", :as => :join_company
  post '/invite' => "profile#invite_users", :as => :invite_users
  get '/join_playspace/:invite_code' => "company#accept_invitation", :as => :accept_invitation

  get '/game/:game_slug' => "game#game_data", :as => :fetch_game_data

  get '/feedback/:type' => "feedback#show", :as => :show_feedback
  post '/feedback/:type' => "feedback#submit", :as => :submit_feedback
end

app/models/feedback.rb
# == Schema Information
#
# Table name: feedbacks
#
#  id            :bigint           not null, primary key
#  feedback_type :string
#  score         :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  employee_id   :bigint           not null
#
# Indexes
#
#  index_feedbacks_on_employee_id  (employee_id)
#
# Foreign Keys
#
#  fk_rails_...  (employee_id => employees.id)
#
class Feedback < ApplicationRecord
  belongs_to :employee
  FEEDBACK_TYPES = %w(recommend need)

  validates :feedback_type, allow_nil: false, inclusion: { in: FEEDBACK_TYPES }
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  before_action :authenticate_user!
  def show
    @type = params[:type]
  end

  def submit
    feedback_type, score = params.require([:type, :score])
    user = current_user
    employee = user&.employee

    Feedback.create!(employee: employee, feedback_type: feedback_type, score: score&.to_i)

    message = "New feedback from #{user.name}(#{user.email}) of #{employee.company.name} : "

    if feedback_type == 'recommend'
      message += "Likehood to recommend to others: #{score}/10"
    else
      feelings = ["", "Not Disappointed", "Somewhat disappointed", "Very disappointed"]
      message += "Feeling if they can't use jally: #{feelings[score&.to_i]}"
    end

    Slack.send_message("#user-activity", message)

    redirect_to root_path
  end
end

app/views/feedback/show.html.erb
<div class="feedback-container">
  <% if @type == 'need' %>
    <h2 class="title has-text-centered">How would you feel if you could no longer use Jally?</h2>
    <%= form_with url: submit_feedback_path(@type), method: :post, class: 'has-text-centered',
                  local: true do |f| %>
      <div class="field mt-3 mb-6 has-text-left">
        <%= f.radio_button :score, 3 %>
        <%= f.label :score, "Very Disappointed", :value => "3"  %><br /><br />
        <%= f.radio_button :score, 2 %>
        <%= f.label :score, "Somewhat disappointed", :value => "2" %><br /><br />
        <%= f.radio_button :score, 1 %>
        <%= f.label :score, "Not disappointed", :value => "1" %>
      </div>
      <%= f.submit "Submit", class: "jally-button-small"%>
    <% end %>
  <% else %>
    <h2 class="title has-text-centered">How likely are you to recommend Jally to other teammates or friends?</h2>
    <%= form_with url: submit_feedback_path(@type), method: :post, class: 'has-text-centered',
                  local: true do |f| %>
      <div class="field mt-3 mb-6 boxx">
        <div class="mb-2 rating">
          <%= f.radio_button :score, 10 %>
          <%= f.label :score, "10", :value => "10"  %>
          <%= f.radio_button :score, 9 %>
          <%= f.label :score, "9", :value => "9" %>
          <%= f.radio_button :score, 8 %>
          <%= f.label :score, "8", :value => "8" %>
          <%= f.radio_button :score, 7 %>
          <%= f.label :score, "7", :value => "7" %>
          <%= f.radio_button :score, 6 %>
          <%= f.label :score, "6", :value => "6" %>
          <%= f.radio_button :score, 5 %>
          <%= f.label :score, "5", :value => "5" %>
          <%= f.radio_button :score, 4 %>
          <%= f.label :score, "4", :value => "4" %>
          <%= f.radio_button :score, 3 %>
          <%= f.label :score, "3", :value => "3" %>
          <%= f.radio_button :score, 2 %>
          <%= f.label :score, "2", :value => "2" %>
          <%= f.radio_button :score, 1 %>
          <%= f.label :score, "1", :value => "1" %>
        </div>
        <span class="not-likely">Not Likely</span>
        <span class="extremely-likely">Extremely Likely</span>
      </div>
      <%= f.submit "Submit", class: "jally-button-small"%>
    <% end %>
  <% end %>
</div>